// Simple Bengali/English language detection via Unicode range check
// Bengali block: U+0980–U+09FF

export type AppLanguage = 'en' | 'bn';

export function detectLanguage(text: string): AppLanguage {
  for (const char of text) {
    const code = char.codePointAt(0);
    if (code >= 0x0980 && code <= 0x09FF) {
      return 'bn';
    }
  }
  return 'en';
}

export function getLabels(lang: AppLanguage) {
  const labels = {
    en: {
      appName: 'InfoQuest',
      subtitle: 'by Arup',
      searchPlaceholder: 'Search any topic...',
      search: 'Search',
      searching: 'Searching...',
      sectionInfo: 'What We Found',
      sectionNews: 'Latest News',
      downloadPdf: 'Download PDF',
      downloadDocx: 'Download Word',
      noResults: 'No results found. Try a different keyword.',
      history: 'Search History',
      clearHistory: 'Clear History',
      noHistory: 'No search history yet.',
      brief: 'Brief',
      detailed: 'Detailed',
      combineLabel: 'Combine Web + AI',
      engineLabel: 'Search Engine',
      progressSearching: 'Searching the web…',
      progressGathering: 'Gathering news…',
      progressFormatting: 'Formatting your report…',
      progressDone: 'Report ready!',
      footerText: 'Generated by InfoQuest by Arup',
      coverTitle: 'Research Report',
      coverSearched: 'Searched:',
      coverDate: 'Date:',
      coverEngine: 'Researched via:',
      sourceLabel: 'Source',
      dateLabel: 'Date',
      newsPlaceholder: 'News articles will appear here...',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      deleteConfirm: 'Delete this search?',
      reDownload: 'Re-download',
      viewReport: 'View Report',
      backToSearch: 'Back to Search',
      loadingReport: 'Loading report...',
    },
    bn: {
      appName: 'InfoQuest',
      subtitle: 'অরূপ দ্বারা',
      searchPlaceholder: 'যেকোনো বিষয় অনুসন্ধান করুন...',
      search: 'অনুসন্ধান',
      searching: 'অনুসন্ধান করা হচ্ছে...',
      sectionInfo: 'যা জানা গেল',
      sectionNews: 'সাম্প্রতিক সংবাদ',
      downloadPdf: 'PDF ডাউনলোড',
      downloadDocx: 'Word ডাউনলোড',
      noResults: 'কোনো ফলাফল পাওয়া যায়নি। অন্য কীওয়ার্ড চেষ্টা করুন।',
      history: 'সার্চ ইতিহাস',
      clearHistory: 'ইতিহাস মুছুন',
      noHistory: 'এখনো কোনো সার্চ ইতিহাস নেই।',
      brief: 'সংক্ষিপ্ত',
      detailed: 'বিস্তারিত',
      combineLabel: 'ওয়েব + AI যুক্ত করুন',
      engineLabel: 'সার্চ ইঞ্জিন',
      progressSearching: 'ওয়েব অনুসন্ধান করা হচ্ছে…',
      progressGathering: 'সংবাদ সংগ্রহ করা হচ্ছে…',
      progressFormatting: 'আপনার রিপোর্ট ফর্ম্যাট করা হচ্ছে…',
      progressDone: 'রিপোর্ট প্রস্তুত!',
      footerText: 'InfoQuest by Arup দ্বারা তৈরি',
      coverTitle: 'গবেষণা রিপোর্ট',
      coverSearched: 'অনুসন্ধান:',
      coverDate: 'তারিখ:',
      coverEngine: 'গবেষণার মাধ্যম:',
      sourceLabel: 'উৎস',
      dateLabel: 'তারিখ',
      newsPlaceholder: 'সংবাদ প্রবন্ধগুলি এখানে দেখাবে...',
      darkMode: 'ডার্ক মোড',
      lightMode: 'লাইট মোড',
      deleteConfirm: 'এই সার্চটি মুছে ফেলবেন?',
      reDownload: 'পুনরায় ডাউনলোড',
      viewReport: 'রিপোর্ট দেখুন',
      backToSearch: 'সার্চে ফিরুন',
      loadingReport: 'রিপোর্ট লোড হচ্ছে...',
    },
  };
  return labels[lang];
}
