import { Language } from "./types";

/**
 * Detects whether a string is predominantly Bengali or English using the
 * Unicode Bengali block (U+0980–U+09FF). No NLP library required.
 */
export function detectLanguage(text: string): Language {
  const bengaliMatches = text.match(/[\u0980-\u09FF]/g);
  const bengaliCount = bengaliMatches ? bengaliMatches.length : 0;

  const letterMatches = text.match(/[\p{L}]/gu);
  const letterCount = letterMatches ? letterMatches.length : 0;

  if (letterCount === 0) return "en";

  return bengaliCount / letterCount > 0.3 ? "bn" : "en";
}

export interface UiStrings {
  appName: string;
  byline: string;
  tagline: string;
  searchPlaceholder: string;
  searchButton: string;
  engineLabel: string;
  modelLabel: string;
  modelLoading: string;
  modelUnavailable: string;
  combineLabel: string;
  lengthLabel: string;
  brief: string;
  detailed: string;
  dateRangeLabel: string;
  dateAny: string;
  date24h: string;
  dateWeek: string;
  dateMonth: string;
  dateYear: string;
  progressSearching: string;
  progressGathering: string;
  progressFormatting: string;
  progressDone: string;
  keywordSummary: string;
  latestNews: string;
  researchedVia: string;
  serialLabel: string;
  newsTitleLabel: string;
  briefDescriptionLabel: string;
  fullNewsLinkLabel: string;
  downloadPdf: string;
  downloadDocx: string;
  history: string;
  noHistory: string;
  reDownload: string;
  clearHistory: string;
  noResults: string;
  source: string;
  footer: string;
  apiKeyMissing: string;
  shareLink: string;
  linkCopied: string;
  darkMode: string;
}

export const UI_STRINGS: Record<Language, UiStrings> = {
  en: {
    appName: "InfoQuest",
    byline: "by Arup",
    tagline: "Search. Discover. Understand.",
    searchPlaceholder: "Search a topic in Bengali or English…",
    searchButton: "Research",
    engineLabel: "Search Engine",
    modelLabel: "AI Model (free, via OpenRouter)",
    modelLoading: "Loading free models…",
    modelUnavailable: "No free models available",
    combineLabel: "Combine Web + AI",
    lengthLabel: "Report length",
    brief: "Brief",
    detailed: "Detailed",
    dateRangeLabel: "News date range",
    dateAny: "Any time",
    date24h: "Past 24 hours",
    dateWeek: "Past week",
    dateMonth: "Past month",
    dateYear: "Past year",
    progressSearching: "Searching the web…",
    progressGathering: "Gathering news…",
    progressFormatting: "Formatting your report…",
    progressDone: "Report ready",
    keywordSummary: "Keyword Summary",
    latestNews: "Latest News",
    researchedVia: "Researched via",
    serialLabel: "Serial",
    newsTitleLabel: "News Title",
    briefDescriptionLabel: "Brief Description",
    fullNewsLinkLabel: "Full News Link",
    downloadPdf: "Download as PDF",
    downloadDocx: "Download as Word (.docx)",
    history: "Search History",
    noHistory: "No past reports yet.",
    reDownload: "Re-download",
    clearHistory: "Clear history",
    noResults: "No results yet — try a search above.",
    source: "Source",
    footer: "Generated by InfoQuest by Arup",
    apiKeyMissing: "API key not configured",
    shareLink: "Copy shareable link",
    linkCopied: "Link copied",
    darkMode: "Dark mode"
  },
  bn: {
    appName: "InfoQuest",
    byline: "by Arup",
    tagline: "খুঁজুন। আবিষ্কার করুন। জানুন।",
    searchPlaceholder: "বাংলা বা ইংরেজিতে একটি বিষয় লিখুন…",
    searchButton: "অনুসন্ধান করুন",
    engineLabel: "সার্চ ইঞ্জিন",
    modelLabel: "এআই মডেল (ফ্রি, ওপেনরাউটার এর মাধ্যমে)",
    modelLoading: "ফ্রি মডেল লোড হচ্ছে…",
    modelUnavailable: "কোনো ফ্রি মডেল পাওয়া যায়নি",
    combineLabel: "ওয়েব + এআই একত্রিত করুন",
    lengthLabel: "রিপোর্টের দৈর্ঘ্য",
    brief: "সংক্ষিপ্ত",
    detailed: "বিস্তারিত",
    dateRangeLabel: "সংবাদের সময়কাল",
    dateAny: "যেকোনো সময়",
    date24h: "গত ২৪ ঘণ্টা",
    dateWeek: "গত সপ্তাহ",
    dateMonth: "গত মাস",
    dateYear: "গত বছর",
    progressSearching: "ওয়েবে খোঁজা হচ্ছে…",
    progressGathering: "সংবাদ সংগ্রহ করা হচ্ছে…",
    progressFormatting: "রিপোর্ট প্রস্তুত করা হচ্ছে…",
    progressDone: "রিপোর্ট প্রস্তুত",
    keywordSummary: "কীওয়ার্ড সারাংশ",
    latestNews: "সাম্প্রতিক সংবাদ",
    researchedVia: "গবেষণার মাধ্যম",
    serialLabel: "ক্রমিক",
    newsTitleLabel: "সংবাদ শিরোনাম",
    briefDescriptionLabel: "সংক্ষিপ্ত বিবরণ",
    fullNewsLinkLabel: "সম্পূর্ণ সংবাদ লিংক",
    downloadPdf: "পিডিএফ ডাউনলোড করুন",
    downloadDocx: "ওয়ার্ড (.docx) ডাউনলোড করুন",
    history: "অনুসন্ধানের ইতিহাস",
    noHistory: "এখনো কোনো রিপোর্ট নেই।",
    reDownload: "পুনরায় ডাউনলোড",
    clearHistory: "ইতিহাস মুছুন",
    noResults: "এখনো কোনো ফলাফল নেই — উপরে অনুসন্ধান করুন।",
    source: "সূত্র",
    footer: "InfoQuest by Arup দ্বারা তৈরি",
    apiKeyMissing: "এপিআই কী কনফিগার করা নেই",
    shareLink: "শেয়ারযোগ্য লিংক কপি করুন",
    linkCopied: "লিংক কপি হয়েছে",
    darkMode: "ডার্ক মোড"
  }
};
